Df 160/ add s3 image in notification table
dehixorg/dehix_admin_frontend pull request #58
Opened 2024-11-21 17:40 UTC by AyushGiri190

![image](https://github.com/user-attachments/assets/71bc3864-bd89-489a-851b-31feecfe2ee4)
![image](https://github.com/user-attachments/assets/cd40030d-c4b2-4585-8806-ddda4e2ff857)

2024-11-24 19:25 UTC, Divesh-singh commented on src/components/Notification/addNotify.tsx
> +        alert('File size exceeds the 2MB limit.');
here too

2024-11-24 19:26 UTC, Divesh-singh commented on src/components/Notification/addNotify.tsx
> +      const { Location } = postResponse.data.data;
add null checks

2024-11-24 19:28 UTC, Divesh-singh commented on src/components/Notification/notifyTable.tsx
> +        setUserData(response.data.data||[]);
add null checks here

2024-11-24 19:29 UTC, Divesh-singh requested changes
address comments

2024-11-30 12:15 UTC, Divesh-singh commented on src/components/Notification/addNotify.tsx
> +        alert(`File size exceeds the ${sizeInMb} limit.`);
Add MB after placeholder in alert

2024-12-01 16:00 UTC, Divesh-singh commented
Resolve conflict

2024-12-01 16:56 UTC, AyushGiri190 commented
> Resolve conflict
resolved

2024-12-05 04:13 UTC, merged